apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
spec:
  containers:
  - name: alpine-container
    image: alpine
    command: ["tail", "-f", "/dev/null"] # Para mantener el contenedor en ejecución

