apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: mateogonzalezamortegui/backend-adopt-pet #fff
        ports:
        - containerPort: 3001  # Puerto por defecto en el que escucha NestJS
