apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: tu_imagen_frontend:etiqueta
        ports:
        - containerPort: 80  # El puerto en el que escucha tu frontend
