---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mongo:22.04
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: database
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: database
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
