apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: my-vlan
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: my-vlan
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001

---

apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: my-vlan
spec:
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
